################################################################################
# Copyright (C) 2016-2021 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell cop-
# ies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IM-
# PLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNE-
# CTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################

###################################################
# This file was generated by Tensile:             #
# https://github.com/ROCm/Tensile                 #
###################################################


set( TensileClient_KERNELS
  ${CMAKE_SOURCE_DIR}/Kernels/Cijk_Ailk_Bjlk_HHS_BH_MT64x64x16_MI16x16x16x1_SNQgSZHfB5BEvZvz82TorrWZSVvmApBkw2iSktlJe0CgI=.h
  ${CMAKE_SOURCE_DIR}/Kernels/Cijk_Ailk_Bjlk_HHS_BH_MT64x64x16_MI16x16x16x1_SNQgSZHfB5BEvZvz82TorrWZSVvmApBkw2iSktlJe0CgI=.cpp
  ${CMAKE_SOURCE_DIR}/Kernels/Cijk_Ailk_Bjlk_HHS_BH_MT64x64x16_MI16x16x16x1_SNtIFkQumpZ5ozgQ1aG22JJmxcRIRXtOhZo5WMuR6skSs=.h
  ${CMAKE_SOURCE_DIR}/Kernels/Cijk_Ailk_Bjlk_HHS_BH_MT64x64x16_MI16x16x16x1_SNtIFkQumpZ5ozgQ1aG22JJmxcRIRXtOhZo5WMuR6skSs=.cpp
  ${CMAKE_SOURCE_DIR}/Kernels/Cijk_Ailk_Bjlk_HHS_BH_MT64x64x16_MI16x16x16x1_SNHAIPDLT5e_SekWPJ14SY-2rxntDNiZfq_K4g0ivrS2Q=.h
  ${CMAKE_SOURCE_DIR}/Kernels/Cijk_Ailk_Bjlk_HHS_BH_MT64x64x16_MI16x16x16x1_SNHAIPDLT5e_SekWPJ14SY-2rxntDNiZfq_K4g0ivrS2Q=.cpp
  ${CMAKE_SOURCE_DIR}/Kernels/Cijk_Ailk_Bjlk_HHS_BH_MT64x64x16_MI16x16x16x1_SNlHnyBZtnE3IRvTemt1jOPuPyvt3yl5A4cBI2E0Thmyo=.h
  ${CMAKE_SOURCE_DIR}/Kernels/Cijk_Ailk_Bjlk_HHS_BH_MT64x64x16_MI16x16x16x1_SNlHnyBZtnE3IRvTemt1jOPuPyvt3yl5A4cBI2E0Thmyo=.cpp
  )
set( TensileClient_SOURCE
  ${CMAKE_SOURCE_DIR}/TensileTypes.h
  ${CMAKE_SOURCE_DIR}/tensile_bfloat16.h
  ${CMAKE_SOURCE_DIR}/tensile_float8_bfloat8.h
  ${CMAKE_SOURCE_DIR}/hip_f8_impl.h
  ${CMAKE_SOURCE_DIR}/KernelHeader.h
  )

